sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t RickyHsieh/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true RickyHsieh/docker-react-practice npm run test
