sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ricky/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true ricky/docker-react-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-practice"
  env: "Docker-practice-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-897523482061"
  bucket_path: "docker-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY